### ISSUE TITLE
#hacktoberfest issue - Just add any content on docker

### ISSUE THREAD

**Issue by Shinobi555** [Shinobi555/Hacktoberfest_2k24#1]
## Description
- Just add any thing about the Docker.
- It can be a code or Non Code Contribution.
> Examples: sample code, project, resources for learning etc.

**Just add any thing about docker so that we can learn anything new.**
## Learn and Let Learn.

**Comment by KarthikeyaEnge** [comment]
I want to Participate, can you assign it to me

**Comment by Yaser-123** [comment]
i don't know much coding can u assign me some task for hacktoberfest @Shinobi555

**Comment by Shinobi555** [comment]
Sure @Yaser-123 !!, U can add any thing like link of a website that is helpful about docker or coding etc. or can add any thing on coding, cloud like an article etc.

**Comment by Yaser-123** [comment]
@Shinobi555 really appreciate you help brother!

**Comment by Yaser-123** [comment]
@Shinobi555  done bro created a pr #8

**Comment by Shinobi555** [comment]
merged!!

**Comment by Yaser-123** [comment]
thanks bro is there any other other issues i can work with c++ and front-end @Shinobi555

**Comment by Shinobi555** [comment]
@Yaser-123 I will open a new issue for frontend

**Comment by Yaser-123** [comment]
yeah ok!

**Comment by Shinobi555** [comment]
https://github.com/Shinobi555/Hacktoberfest_2k24/issues/9 go to this issue any contribute

**Comment by hasin-zaman** [comment]
Hello @Shinobi555 can you assign me this issue.
